---
title: "C.E.A.P analysis"
author: "José Benardi de Souza Nunes"
date: 30/08/2018
output:
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r}
library(tidyverse)
library(lubridate)
library(here)

theme_set(theme_bw())
```

```{r}
data <- read_csv(here::here("data/dadosCEAP.csv"),
                 progress = F,
                 col_types = cols(
                   nomeParlamentar = col_character(),
                   idCadastro = col_integer(),
                   sgUF = col_character(),
                   sgPartido = col_character(),
                   tipoDespesa = col_character(),
                   especDespesa = col_character(),
                   fornecedor = col_character(),
                   CNPJCPF = col_character(),
                   tipoDocumento = col_integer(),
                   dataEmissao = col_character(),
                   valorDocumento = col_double(),
                   valorGlosa = col_integer(),
                   valorLíquido = col_double())) %>%
  mutate(dataEmissao = parse_date_time(dataEmissao,"%Y-%m-%d %H:%M:%S"),
         year_month = paste(lubridate::year(dataEmissao),
                            lubridate::month(dataEmissao),sep = "-"),
         tipoDespesa = toupper(tipoDespesa))

state_info <- read_csv(here::here("/data/limiteMensalCEAP.csv"),
                       progress = F,
                       col_types = cols(
                         UF = col_character(),
                         limite_mensal = col_double()))

data %>% 
  full_join(state_info,
            by = c("sgUF" = "UF")) -> data

data %>%
  glimpse()
```

```{r}
data %>%
  mutate(week_day = wday(dataEmissao),
         is_weekend = (week_day == 1) |
                         (week_day == 7)) -> data

data %>%
  select(dataEmissao,
         week_day,
         is_weekend) %>%
  sample_n(5)
```

```{r}
data %>%
  na.omit(is_weekend) %>%
  mutate(total = sum(valorLíquido)) %>%
  group_by(total,
           is_weekend) %>%
  summarize(total_expense = sum(valorLíquido)) %>%
  mutate(fract = total_expense/total) %>%
  ggplot(aes(is_weekend,fract)) +
  geom_bar(stat="identity") +
    labs(x="Is it a weekend",
       y="Percentage (%)")
```

```{r}
data %>%
  group_by(is_weekend,sgPartido) %>%
  summarize(total_expense = sum(valorLíquido)) %>%
  na.omit(is_weekend) %>%
  ggplot(aes(reorder(sgPartido,
                     total_expense),
             total_expense,
             fill=is_weekend)) +
  geom_bar(stat="identity") + 
  labs(x="Political parties",
       y="Total expense (R$)") +
  theme(axis.text.x = element_text(angle = 60,
                                   hjust = 1))
```

```{r}
data %>%
  filter(is_weekend) %>%
  group_by(is_weekend,sgPartido) %>%
  summarize(total_expense = sum(valorLíquido)) %>%
  na.omit(is_weekend) %>%
  ggplot(aes(reorder(sgPartido,
                     total_expense),
             total_expense)) +
  geom_bar(stat="identity",
           fill="#00BFC4") + 
  labs(x="Political parties",
       y="Total expense (R$)") +
  theme(axis.text.x = element_text(angle = 60,
                                   hjust = 1))
```

```{r}
data %>%
  na.omit(is_weekend,
          sgPartido) %>%
  group_by(sgPartido) %>%
  mutate(total = sum(valorLíquido)) %>%
  ungroup() %>%
  group_by(total,
           sgPartido,
           is_weekend) %>%
  summarize(total_expense = sum(valorLíquido)) %>%
  mutate(fract = total_expense/total) %>%
  filter(is_weekend) %>%
  ggplot(aes(reorder(sgPartido,fract),
             fract)) +
  geom_bar(stat="identity") +
    labs(x="Is it a weekend",
       y="Percentage (%)") +
  theme(axis.text.x = element_text(angle = 60,
                                   hjust = 1))
```

```{r}
data %>%
  group_by(fornecedor) %>%
  summarize(total_expense = sum(valorLíquido)) %>%
  top_n(10, wt=total_expense) %>%
  mutate(fornecedor = toupper(fornecedor)) %>%
  ggplot(aes(reorder(fornecedor,
                     total_expense),
             total_expense)) +
  geom_bar(stat="identity") + 
  labs(x="Supplier",
       y="Total expense (R$)") +
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1)) +
  coord_flip() 
```
